AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
